volumes:
  data:

services:
  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: hamza123
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_DATABASE: strapi
